// Generated by CoffeeScript 1.10.0
(function() {
  var GIF_HEADER, JPEG_HEADER, PNG_HEADER, TIFF_HEADER_I, TIFF_HEADER_M, matchHeader;

  GIF_HEADER = new Buffer([0x47, 0x49, 0x46, 0x38]);

  PNG_HEADER = new Buffer([0x89, 0x50, 0x4E, 0x47]);

  JPEG_HEADER = new Buffer([0xFF, 0xD8, 0xFF]);

  TIFF_HEADER_I = new Buffer([0x49, 0x49, 0x2A, 0x00]);

  TIFF_HEADER_M = new Buffer([0x4D, 0x4D, 0x00, 0x2A]);

  matchHeader = function(header, bytes) {
    return bytes.slice(0, header.length).toString("hex") === header.toString("hex");
  };

  module.exports = {
    identifyFormatOf: function(buffer) {
      var bytes;
      if (buffer.length >= 4) {
        bytes = buffer.slice(0, 4);
        switch (false) {
          case !matchHeader(GIF_HEADER, bytes):
            return "GIF";
          case !matchHeader(PNG_HEADER, bytes):
            return "PNG";
          case !matchHeader(JPEG_HEADER, bytes):
            return "JPEG";
          case !matchHeader(TIFF_HEADER_I, bytes):
            return "TIFF";
          case !matchHeader(TIFF_HEADER_M, bytes):
            return "TIFF";
        }
      }
    }
  };

}).call(this);
