// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    scanHeader: function() {
      this.scan_endianness();
      if (this.scan_tag_mark()) {
        return this.scan_and_skip_to_offset();
      }
    },
    scan_endianness: function() {
      var one, ref, two;
      ref = [this.readChar(), this.readChar()], one = ref[0], two = ref[1];
      return this.big = (one === two && two === 0x4D) ? true : false;
    },
    scan_tag_mark: function() {
      return this.readShort() === 0x002A;
    },
    scan_and_skip_to_offset: function() {
      var offset;
      offset = this.readLong();
      return this.skipTo(offset);
    },
    scan_ifd: function(callback) {
      var entry_count, i, j, offset, ref, results, tag;
      offset = this.position;
      entry_count = this.readShort();
      results = [];
      for (i = j = 0, ref = entry_count; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.skipTo(offset + 2 + (12 * i));
        tag = this.readShort();
        results.push(callback(tag));
      }
      return results;
    },
    readIntegerValue: function() {
      var type;
      type = this.readShort();
      this.advance(4);
      if (type === 3) {
        return this.readShort();
      } else if (type === 4) {
        return this.readLong();
      } else {
        return this.throwScanError();
      }
    },
    skipTo: function(position) {
      this.position = position;
      if (this.position > this.data.length) {
        return this.throwScanError();
      }
    }
  };

}).call(this);
